// 📍 Ruta: src/features/admin/kaizen/kaizen.knowledge.ts

import type { KaizenInsightCategory, KaizenTip } from "./kaizen.types";

export type KaizenQuickPromptGroup = {
  title: string;
  category: KaizenInsightCategory;
  prompts: string[];
};

export const KAIZEN_FOOD_TRUCK_TIPS: KaizenTip[] = [
  {
    id: "inventory_001",
    title: "Cuenta inventario al cierre",
    body: "Un conteo corto al cerrar turno ayuda a detectar faltantes antes del siguiente servicio. Prioriza tortillas, carnes, bebidas, salsas, empaques y productos agotados.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "inventory_002",
    title: "Usa mínimos por item",
    body: "Cada producto sensible debe tener un mínimo claro. Si el stock cae debajo del mínimo, Kaizen debe tratarlo como prioridad antes de horas pico.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "inventory_003",
    title: "Separa ingredientes de empaque",
    body: "No mezcles comida con insumos operativos. Bolsas, guantes, charolas y servilletas deben revisarse como operación, no como comida vendida.",
    category: "inventory",
    level: "pro",
  },
  {
    id: "inventory_004",
    title: "Revisa empaques antes del rush",
    body: "Un food truck puede tener comida lista, pero perder ventas si faltan bolsas, charolas, vasos o servilletas en hora pico.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "inventory_005",
    title: "Etiqueta fechas al recibir producto",
    body: "Cuando llegue producto nuevo, marca fecha de entrada. Eso facilita usar primero lo más antiguo y reduce producto vencido.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "inventory_006",
    title: "Aplica primero en entrar primero en salir",
    body: "Usa primero el producto más viejo antes de abrir producto nuevo. Este hábito baja desperdicio y mejora control.",
    category: "inventory",
    level: "pro",
  },
  {
    id: "inventory_007",
    title: "No compres solo por intuición",
    body: "Antes de comprar, revisa ventas recientes, stock actual y merma. Comprar por costumbre puede generar sobrantes o faltantes.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "inventory_008",
    title: "Identifica inventario invisible",
    body: "Salsas, tapas, popotes, guantes y bolsas suelen acabarse sin notarse. Ponlos en conteo rápido del día.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "inventory_009",
    title: "Divide stock crítico y stock de respaldo",
    body: "Ten una parte lista para operación y otra de respaldo. Así puedes detectar cuando ya estás consumiendo el colchón de seguridad.",
    category: "inventory",
    level: "pro",
  },
  {
    id: "inventory_010",
    title: "Registra ajustes manuales",
    body: "Cuando cambies stock a mano, deja nota. Sin notas, después no sabrás si fue venta, merma, error o uso operativo.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "inventory_011",
    title: "Mide productos con unidades reales",
    body: "Usa unidades claras como lb, pack, box, bottle o unidad. Mezclar cajas con piezas vuelve confuso el inventario.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "inventory_012",
    title: "Revisa productos congelados o refrigerados",
    body: "Los productos fríos requieren control especial. Un descuido puede convertirse en merma grande y riesgo operativo.",
    category: "inventory",
    level: "pro",
  },
  {
    id: "inventory_013",
    title: "No llenes el truck de productos lentos",
    body: "El espacio en food truck es limitado. Prioriza lo que se vende, se prepara rápido y no estorba operación.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "inventory_014",
    title: "Ten lista de compra sugerida",
    body: "Cuando haya varios productos bajo mínimo, convierte la alerta en lista de compra. Eso ahorra tiempo y evita olvidar insumos.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "inventory_015",
    title: "Audita diferencias grandes",
    body: "Si el sistema dice una cantidad y físicamente hay otra muy distinta, registra ajuste y busca causa: error de captura, merma no registrada o uso operativo.",
    category: "inventory",
    level: "pro",
  },
  {
    id: "inventory_016",
    title: "Cuenta bebidas por sabor",
    body: "Las bebidas parecen simples, pero sabores específicos se agotan distinto. Separarlas ayuda a comprar mejor.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "inventory_017",
    title: "Cuida tortillas y masa",
    body: "En comida mexicana, tortillas y masa son insumos sensibles. Si fallan, afectan muchos productos a la vez.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "inventory_018",
    title: "Marca productos agotados rápido",
    body: "Si un item se acaba, márcalo pronto para evitar vender algo que cocina no puede preparar.",
    category: "inventory",
    level: "pro",
  },
  {
    id: "inventory_019",
    title: "Revisa stock después de promociones",
    body: "Una promo puede mover más producto de lo normal. Después de promociones revisa inventario antes del siguiente turno.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "inventory_020",
    title: "Crea rutina de 10 minutos",
    body: "Un conteo de 10 minutos bien hecho vale más que revisar todo de prisa una vez por semana.",
    category: "inventory",
    level: "basic",
  },
  {
    id: "waste_001",
    title: "Registra toda merma",
    body: "Aunque parezca pequeña, registra errores, derrames, cortesías, vencidos y uso operativo. Lo que no se mide parece invisible.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_002",
    title: "Separa uso operativo",
    body: "Guantes, bolsas, servilletas, limpieza y empaques deben ir como uso operativo. Así no se confunden con comida de staff.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_003",
    title: "Separa consumo interno",
    body: "Comida o bebida para empleados debe registrarse como consumo interno. Esto aclara cuánto se consume dentro del negocio.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_004",
    title: "Controla cortesías",
    body: "Una cortesía puede salvar un cliente, pero debe registrarse. Si no, parece pérdida desconocida.",
    category: "waste",
    level: "pro",
  },
  {
    id: "waste_005",
    title: "Errores de cocina con nota",
    body: "Si cocina preparó mal algo, registra error de cocina con nota. Después podrás ver si se repite el mismo problema.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_006",
    title: "Mide derrames y caídas",
    body: "Derrames de bebida, salsas o ingredientes deben registrarse. Muchas pérdidas chicas juntas pesan al final del mes.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_007",
    title: "Detecta desperdicio de empaques",
    body: "Si guantes, bolsas o servilletas bajan demasiado rápido, puede haber desperdicio, exceso de uso o falta de entrenamiento.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_008",
    title: "No ocultes mermas",
    body: "La merma no es castigo; es información. Si el equipo la registra sin miedo, el negocio mejora.",
    category: "waste",
    level: "pro",
  },
  {
    id: "waste_009",
    title: "Revisa producto vencido",
    body: "Si algo vence seguido, quizá se está comprando demasiado, se rota mal o no se vende lo suficiente.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_010",
    title: "Diferencia regalo de promoción",
    body: "Un regalo puntual no es lo mismo que promo planeada. Separarlo ayuda a medir bien ingresos y pérdidas.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_011",
    title: "Analiza merma semanal",
    body: "Una revisión semanal de merma muestra patrones: productos problemáticos, horarios difíciles o empleados que necesitan apoyo.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_012",
    title: "Cuida salsas y toppings",
    body: "Salsas, cebolla, cilantro y toppings pueden desperdiciarse por porciones mal controladas. Usa recipientes y porciones consistentes.",
    category: "waste",
    level: "pro",
  },
  {
    id: "waste_013",
    title: "Registra pruebas de cocina",
    body: "Si hacen pruebas de recetas o capacitación, regístralo como consumo interno o ajuste. No debe confundirse con venta perdida.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_014",
    title: "Merma alta requiere acción",
    body: "Si la pérdida estimada sube, no solo lo mires: define acción concreta como porcionar mejor, entrenar o ajustar compras.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_015",
    title: "No mezcles robo con merma",
    body: "Si detectas faltantes raros, usa notas. No todo es merma normal; algunos patrones pueden indicar mal control.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_016",
    title: "Usa fotos si hay dudas",
    body: "Para errores grandes, una foto interna ayuda a entender qué pasó sin discutir después.",
    category: "waste",
    level: "pro",
  },
  {
    id: "waste_017",
    title: "Evita doble apertura",
    body: "Abrir varios paquetes del mismo insumo aumenta riesgo de desperdicio. Termina uno antes de abrir otro cuando sea posible.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_018",
    title: "Porciona antes del rush",
    body: "Porcionar insumos antes de horas pico reduce errores, acelera cocina y baja desperdicio.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_019",
    title: "Revisa charolas y vasos",
    body: "Empaques dañados también cuestan. Si hay cajas golpeadas o vasos rotos, regístralo como producto dañado.",
    category: "waste",
    level: "basic",
  },
  {
    id: "waste_020",
    title: "Mide merma por motivo",
    body: "El motivo importa más que el total. Error de cocina, vencido y uso operativo tienen soluciones diferentes.",
    category: "waste",
    level: "pro",
  },
  {
    id: "sales_001",
    title: "Empuja bebidas con platillos",
    body: "Las bebidas suelen subir ticket promedio sin complicar cocina. Sugiere bebida con tacos, burritos, tortas o especialidades.",
    category: "sales",
    level: "basic",
  },
  {
    id: "sales_002",
    title: "Crea combos fáciles",
    body: "Los combos deben ser simples de entender en segundos. Si el cajero tarda en explicarlo, el cliente no lo compra en fila.",
    category: "sales",
    level: "basic",
  },
  {
    id: "sales_003",
    title: "Usa producto líder como ancla",
    body: "Si un producto vende mucho, úsalo como base para combos, fotos, posts y recomendaciones en caja.",
    category: "sales",
    level: "pro",
  },
  {
    id: "sales_004",
    title: "No promociones productos lentos sin revisar",
    body: "Un producto lento quizá necesita mejor foto, nombre, ubicación o precio antes de poner descuento.",
    category: "sales",
    level: "basic",
  },
  {
    id: "sales_005",
    title: "Ticket bajo pide upsell",
    body: "Si el ticket promedio está bajo, prueba agregar bebida, extra proteína, salsa especial o upgrade de tamaño.",
    category: "sales",
    level: "basic",
  },
  {
    id: "sales_006",
    title: "Haz ofertas de hora lenta",
    body: "Si hay horas flojas, usa promos limitadas para mover demanda sin saturar horas pico.",
    category: "sales",
    level: "pro",
  },
  {
    id: "sales_007",
    title: "Evita descuentos innecesarios",
    body: "No todo se arregla con descuento. A veces basta con mejor recomendación, combo o visibilidad.",
    category: "sales",
    level: "basic",
  },
  {
    id: "sales_008",
    title: "Mide productos más rápidos",
    body: "En rush conviene empujar productos de preparación rápida para mover fila y evitar estrés en cocina.",
    category: "sales",
    level: "basic",
  },
  {
    id: "sales_009",
    title: "Destaca margen alto",
    body: "Si sabes qué deja mejor margen, dale más presencia en menú y caja. No todo lo más vendido es lo más rentable.",
    category: "sales",
    level: "pro",
  },
  {
    id: "sales_010",
    title: "Ofrece extras simples",
    body: "Extras como queso, bebida o acompañamiento pueden subir ventas sin crear un producto nuevo.",
    category: "sales",
    level: "basic",
  },
  {
    id: "sales_011",
    title: "Usa nombres apetecibles",
    body: "Un nombre claro y sabroso puede vender más que una descripción técnica.",
    category: "sales",
    level: "basic",
  },
  {
    id: "sales_012",
    title: "Menú corto en hora pico",
    body: "Si hay mucha fila, conviene empujar productos principales y evitar opciones que retrasen cocina.",
    category: "sales",
    level: "pro",
  },
  {
    id: "sales_013",
    title: "Prueba combos por semana",
    body: "No cambies todo diario. Prueba un combo por semana y mide si sube ticket promedio.",
    category: "sales",
    level: "basic",
  },
  {
    id: "sales_014",
    title: "Ordena menú por intención",
    body: "Pon arriba productos populares, rentables o rápidos. El orden del menú influye en decisiones.",
    category: "sales",
    level: "basic",
  },
  {
    id: "sales_015",
    title: "Registra ventas entregadas",
    body: "Analiza solo órdenes entregadas para ventas reales. Órdenes canceladas pueden distorsionar el resultado.",
    category: "sales",
    level: "pro",
  },
  {
    id: "sales_016",
    title: "Vende experiencia, no solo comida",
    body: "Frases como recién hecho, bien servido o favorito de la casa ayudan a vender sin bajar precio.",
    category: "sales",
    level: "basic",
  },
  {
    id: "sales_017",
    title: "Cuidado con demasiadas opciones",
    body: "Muchas opciones pueden frenar decisión y cocina. Un menú enfocado suele vender mejor.",
    category: "sales",
    level: "basic",
  },
  {
    id: "sales_018",
    title: "Pregunta natural de upsell",
    body: "En caja funciona mejor una frase simple: ¿le agrego bebida? que una explicación larga.",
    category: "sales",
    level: "pro",
  },
  {
    id: "sales_019",
    title: "Monitorea productos cero ventas",
    body: "Si un producto no se mueve, revisa si está visible, disponible, con buena foto y recomendado por staff.",
    category: "sales",
    level: "basic",
  },
  {
    id: "sales_020",
    title: "Usa datos para precio",
    body: "Antes de subir o bajar precio, revisa ventas, merma, costo y ticket promedio.",
    category: "sales",
    level: "basic",
  },
  {
    id: "operations_001",
    title: "Prepara antes de abrir",
    body: "Antes de abrir, verifica mise en place, bebidas frías, empaques, terminal de pago, cambio y productos críticos.",
    category: "operations",
    level: "basic",
  },
  {
    id: "operations_002",
    title: "Define roles en rush",
    body: "En hora pico cada persona debe saber su rol: caja, cocina, armado, entrega o apoyo. La confusión aumenta tiempos.",
    category: "operations",
    level: "basic",
  },
  {
    id: "operations_003",
    title: "Reduce pasos innecesarios",
    body: "En un food truck, caminar o buscar cosas cuesta tiempo. Pon lo más usado al alcance del área correcta.",
    category: "operations",
    level: "pro",
  },
  {
    id: "operations_004",
    title: "Plan para fila larga",
    body: "Si la fila crece, simplifica recomendaciones, avisa tiempos reales y empuja productos rápidos.",
    category: "operations",
    level: "basic",
  },
  {
    id: "operations_005",
    title: "Comunica agotados",
    body: "Cuando algo se agota, caja y cocina deben saberlo al instante para evitar ventas imposibles.",
    category: "operations",
    level: "basic",
  },
  {
    id: "operations_006",
    title: "Checklist de apertura",
    body: "Usa una lista simple: gas, agua, electricidad, terminal, efectivo, inventario sensible, salsas, empaques y limpieza.",
    category: "operations",
    level: "pro",
  },
  {
    id: "operations_007",
    title: "Checklist de cierre",
    body: "Cierre debe incluir conteo rápido, limpieza, merma, apagado seguro, notas del turno y preparación del siguiente día.",
    category: "operations",
    level: "basic",
  },
  {
    id: "operations_008",
    title: "Tiempos honestos",
    body: "Si hay demora, decir un tiempo real evita frustración. Es mejor prometer 15 minutos y cumplir que decir 5 y fallar.",
    category: "operations",
    level: "basic",
  },
  {
    id: "operations_009",
    title: "Evita cuellos de botella",
    body: "Detecta dónde se detiene la operación: caja, cocción, armado, empaque o entrega. Mejora ese punto primero.",
    category: "operations",
    level: "pro",
  },
  {
    id: "operations_010",
    title: "Orden visible en cocina",
    body: "El panel de cocina debe mostrar prioridades claras. Menos confusión significa menos errores.",
    category: "operations",
    level: "basic",
  },
  {
    id: "operations_011",
    title: "No ignores cancelaciones",
    body: "Cancelaciones pueden indicar stock faltante, errores de captura, tiempos largos o comunicación débil.",
    category: "operations",
    level: "basic",
  },
  {
    id: "operations_012",
    title: "Capacita con escenarios",
    body: "Entrena qué hacer si falta producto, se equivoca orden, falla terminal o llega mucha fila de golpe.",
    category: "operations",
    level: "pro",
  },
  {
    id: "operations_013",
    title: "Mantén estación limpia",
    body: "Una estación limpia reduce errores, mejora velocidad y evita contaminación cruzada.",
    category: "operations",
    level: "basic",
  },
  {
    id: "operations_014",
    title: "Agrupa tareas repetidas",
    body: "Si se repite mucho una acción, prepara lotes pequeños controlados para ganar velocidad sin sacrificar calidad.",
    category: "operations",
    level: "basic",
  },
  {
    id: "operations_015",
    title: "Controla calidad antes de entregar",
    body: "Revisar bolsa antes de entregar evita reclamos, reseñas malas y cortesías innecesarias.",
    category: "operations",
    level: "pro",
  },
  {
    id: "operations_016",
    title: "Notas claras en orden",
    body: "Notas de cliente deben verse bien para cocina. Una nota ignorada puede convertirse en remake o queja.",
    category: "operations",
    level: "basic",
  },
  {
    id: "operations_017",
    title: "Cuida flujo de entrega",
    body: "Separar órdenes listas de órdenes en preparación reduce confusión en ventana.",
    category: "operations",
    level: "basic",
  },
  {
    id: "operations_018",
    title: "Activa modo menú reducido",
    body: "Si cocina está saturada o hay stock bajo, considera vender solo productos rápidos temporalmente.",
    category: "operations",
    level: "pro",
  },
  {
    id: "operations_019",
    title: "Revisa clima y eventos",
    body: "Clima, eventos locales y fines de semana cambian demanda. Prepárate distinto según el día.",
    category: "operations",
    level: "basic",
  },
  {
    id: "operations_020",
    title: "Haz retro de 5 minutos",
    body: "Después de turno fuerte, pregunta: qué faltó, qué sobró, qué se atoró y qué se repite mañana.",
    category: "operations",
    level: "basic",
  },
  {
    id: "loyalty_001",
    title: "Pide teléfono sin hacerlo incómodo",
    body: "Pregunta de forma natural: ¿quiere acumular puntos con su teléfono? Es rápido y crea hábito.",
    category: "loyalty",
    level: "basic",
  },
  {
    id: "loyalty_002",
    title: "Menciona puntos disponibles",
    body: "Cuando el cliente tiene recompensa, díselo en caja. La lealtad funciona mejor cuando el cliente siente beneficio real.",
    category: "loyalty",
    level: "basic",
  },
  {
    id: "loyalty_003",
    title: "Usa recompensas simples",
    body: "Las recompensas deben ser fáciles de entender: bebida gratis, descuento fijo o producto específico.",
    category: "loyalty",
    level: "basic",
  },
  {
    id: "loyalty_004",
    title: "No regales sin medir",
    body: "Si una recompensa se canjea, debe quedar registrada. Así sabes cuánto cuesta retener clientes.",
    category: "loyalty",
    level: "pro",
  },
  {
    id: "loyalty_005",
    title: "Premia frecuencia",
    body: "Una recompensa por visitas frecuentes puede traer más regreso que un descuento general para todos.",
    category: "loyalty",
    level: "basic",
  },
  {
    id: "loyalty_006",
    title: "Promueve loyalty en ventana",
    body: "Un pequeño letrero o frase en caja ayuda a que el cliente se entere del programa.",
    category: "loyalty",
    level: "basic",
  },
  {
    id: "loyalty_007",
    title: "Usa recompensas para horas lentas",
    body: "Puedes crear beneficios que se usen en horarios bajos para mover demanda sin saturar rush.",
    category: "loyalty",
    level: "basic",
  },
  {
    id: "loyalty_008",
    title: "Recupera clientes frecuentes",
    body: "Si alguien compra seguido, trátalo como VIP. Recordar su preferencia aumenta conexión.",
    category: "loyalty",
    level: "pro",
  },
  {
    id: "loyalty_009",
    title: "Evita reglas confusas",
    body: "Si el cliente no entiende cómo gana o canjea puntos, no usará el programa.",
    category: "loyalty",
    level: "basic",
  },
  {
    id: "loyalty_010",
    title: "Mide canjes",
    body: "Muchos puntos acumulados pero pocos canjes puede significar que nadie está explicando el programa.",
    category: "loyalty",
    level: "basic",
  },
  {
    id: "loyalty_011",
    title: "Cortesía controlada gana reseñas",
    body: "Una recompensa bien aplicada puede convertir un error en buena experiencia.",
    category: "loyalty",
    level: "basic",
  },
  {
    id: "loyalty_012",
    title: "No devalues producto premium",
    body: "Evita regalar siempre lo más caro. Usa recompensas con buen balance entre costo y satisfacción.",
    category: "loyalty",
    level: "pro",
  },
  {
    id: "loyalty_013",
    title: "Cliente feliz regresa",
    body: "La lealtad no es solo puntos; también es velocidad, trato, consistencia y buena comida.",
    category: "loyalty",
    level: "basic",
  },
  {
    id: "loyalty_014",
    title: "Entrena al cajero",
    body: "El cajero es quien activa loyalty. Si no lo menciona, el sistema pierde fuerza.",
    category: "loyalty",
    level: "basic",
  },
  {
    id: "loyalty_015",
    title: "Crea metas visibles",
    body: "Frases como te faltan pocos puntos para bebida gratis motivan al cliente a volver.",
    category: "loyalty",
    level: "basic",
  },
  {
    id: "marketing_001",
    title: "Publica ubicación y horario",
    body: "En redes, lo primero que el cliente necesita es saber dónde estás y a qué hora.",
    category: "marketing",
    level: "basic",
  },
  {
    id: "marketing_002",
    title: "Muestra comida real",
    body: "Fotos y videos reales generan más confianza que imágenes demasiado perfectas o falsas.",
    category: "marketing",
    level: "basic",
  },
  {
    id: "marketing_003",
    title: "Graba preparación",
    body: "Videos cortos de carne, tortillas, salsas o bebidas preparándose venden muy bien visualmente.",
    category: "marketing",
    level: "pro",
  },
  {
    id: "marketing_004",
    title: "Promueve producto líder",
    body: "Si algo se vende mucho, súbelo a redes con foto fuerte y llamado claro.",
    category: "marketing",
    level: "basic",
  },
  {
    id: "marketing_005",
    title: "Publica antes de horas pico",
    body: "Sube contenido antes del horario fuerte para generar antojo cuando la gente decide qué comer.",
    category: "marketing",
    level: "basic",
  },
  {
    id: "marketing_006",
    title: "Usa combos en redes",
    body: "Un combo claro con precio y foto ayuda más que publicar todo el menú completo.",
    category: "marketing",
    level: "pro",
  },
  {
    id: "marketing_007",
    title: "Pide reseñas en buen momento",
    body: "Cuando el cliente está feliz o regresa, pide reseña de forma amable.",
    category: "marketing",
    level: "basic",
  },
  {
    id: "marketing_008",
    title: "Responde mensajes rápido",
    body: "Muchos clientes preguntan horario, ubicación o si hay producto disponible. Responder rápido puede cerrar ventas.",
    category: "marketing",
    level: "basic",
  },
  {
    id: "marketing_009",
    title: "Haz contenido de escasez real",
    body: "Si queda poco de un producto popular, publicarlo puede mover ventas, pero solo si es verdad.",
    category: "marketing",
    level: "pro",
  },
  {
    id: "marketing_010",
    title: "Muestra clientes felices con permiso",
    body: "Contenido social con gente real aumenta confianza, siempre con permiso.",
    category: "marketing",
    level: "basic",
  },
  {
    id: "marketing_011",
    title: "No publiques solo ventas",
    body: "Mezcla comida, equipo, preparación, ubicación, historia y promociones.",
    category: "marketing",
    level: "basic",
  },
  {
    id: "marketing_012",
    title: "Promueve loyalty",
    body: "Recuerda en redes que pueden acumular puntos. Muchos no preguntan si no ven el beneficio.",
    category: "marketing",
    level: "pro",
  },
  {
    id: "marketing_013",
    title: "Usa TikTok para antojo",
    body: "Videos de close-up, armado y reacción funcionan mejor que anuncios largos.",
    category: "marketing",
    level: "basic",
  },
  {
    id: "marketing_014",
    title: "Mantén branding constante",
    body: "Colores, logo y tono consistentes hacen que el negocio se vea más profesional.",
    category: "marketing",
    level: "basic",
  },
  {
    id: "marketing_015",
    title: "Publica agotados con cuidado",
    body: "Si algo se agotó, úsalo como señal de demanda y avisa cuándo regresa.",
    category: "marketing",
    level: "pro",
  },
  {
    id: "marketing_016",
    title: "Comparte horarios especiales",
    body: "Cambios de horario, clima o evento deben publicarse claro para evitar clientes perdidos.",
    category: "marketing",
    level: "basic",
  },
  {
    id: "marketing_017",
    title: "Haz foto de menú legible",
    body: "Un menú borroso o difícil de leer pierde clientes. Debe verse bien en teléfono.",
    category: "marketing",
    level: "basic",
  },
  {
    id: "marketing_018",
    title: "Usa llamadas simples",
    body: "Frases como hoy en Houston, tacos listos, ordena aquí o ven por tu horchata funcionan mejor que textos largos.",
    category: "marketing",
    level: "pro",
  },
  {
    id: "marketing_019",
    title: "Mide publicaciones",
    body: "Si un post trae ventas o preguntas, repite formato. Si no mueve nada, cambia foto, hora o mensaje.",
    category: "marketing",
    level: "basic",
  },
  {
    id: "marketing_020",
    title: "Humaniza el truck",
    body: "Mostrar al equipo, proceso y esfuerzo crea conexión más fuerte que solo publicar productos.",
    category: "marketing",
    level: "basic",
  },
];

export const KAIZEN_QUICK_PROMPT_GROUPS: KaizenQuickPromptGroup[] = [
  {
    title: "Operación diaria",
    category: "operations",
    prompts: [
      "¿Qué reviso hoy?",
      "¿Qué hago antes de abrir?",
      "¿Qué debo revisar al cerrar turno?",
      "¿Cómo reduzco tiempos en hora pico?",
      "¿Qué hago si hay mucha fila?",
      "¿Qué puede estar frenando la operación?",
    ],
  },
  {
    title: "Inventario",
    category: "inventory",
    prompts: [
      "¿Qué stock está crítico?",
      "¿Qué debo comprar pronto?",
      "¿Qué inventario sensible debo revisar?",
      "¿Cómo organizo mejor el inventario?",
      "¿Qué productos pueden agotarse?",
      "¿Qué hago con productos lentos?",
    ],
  },
  {
    title: "Ventas",
    category: "sales",
    prompts: [
      "¿Cómo van las ventas?",
      "¿Cómo subo el ticket promedio?",
      "¿Qué combo recomiendas?",
      "¿Qué producto debo empujar?",
      "¿Qué hago si hay pocas ventas?",
      "¿Cómo vendo más bebidas?",
    ],
  },
  {
    title: "Merma",
    category: "waste",
    prompts: [
      "¿Qué hago con merma?",
      "¿Cómo reduzco desperdicio?",
      "¿Cómo clasifico guantes y bolsas?",
      "¿Cómo controlo cortesías?",
      "¿Qué merma debo revisar primero?",
      "¿Cómo detecto pérdidas raras?",
    ],
  },
  {
    title: "Lealtad",
    category: "loyalty",
    prompts: [
      "¿Cómo aumento clientes recurrentes?",
      "¿Cómo uso mejor los puntos?",
      "¿Qué digo en caja sobre lealtad?",
      "¿Cómo promuevo recompensas?",
      "¿Qué clientes debo cuidar más?",
    ],
  },
  {
    title: "Marketing",
    category: "marketing",
    prompts: [
      "¿Qué publico hoy?",
      "¿Cómo uso TikTok mejor?",
      "¿Qué promoción recomiendas?",
      "¿Cómo atraigo más clientes?",
      "¿Cómo promociono el producto líder?",
      "¿Cómo pido reseñas?",
    ],
  },
];
